---
abstract: 'Yet Another RESTful-Archive Service'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::Clustericious::Cluster: 0.08
  Test::Clustericious::Config: 0
  Test::Clustericious::Log: 0
  Test::More: 0
  YAML::XS: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yars
recommends:
  EV: 0
requires:
  Clustericious: 0.9925
  Clustericious::Commands: 0
  Clustericious::Config: 0.21
  Clustericious::Log: 0.11
  File::Find::Rule: 0
  File::HomeDir: 0.91
  Hash::MoreUtils: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Log::Log4perl::CommandLine: 0
  Mojolicious: 4.31
  Number::Bytes::Human: 0.09
  Yars::Client: 0.90
  perl: v5.10.1
resources:
  bugtracker: https://github.com/plicease/yars/issues
  homepage: http://perl.wdlabs.com/Yars/
  repository: git://github.com/plicease/yars.git
version: 1.01
