=head1 NAME

RESTAS -- REST Archive Server

=head1 SYNOPSIS

 RESTAS-Server
 RESTAS-Client

      or

 RESTAS-Yars
 RESTAS-Yarc


=head1 DESCRIPTION

RESTAS is a system for storing files using their MD5 checksums.  It implements a client-server architecture, using REST to communicate.  Constraints encountered during development have resulted in two different implementations: RESTAS-Server/Client and RESTAS-Yars/Yarc.  RESTAS-Server/Client has more features and is used in production, while RESTAS-Yars/Yarc is lighter and built on the Clustericious framework.  


=head1 SEE ALSO

L<RESTAS::Server>

L<RESTAS::Client>

 or 

L<RESTAS::Yars>

L<RESTAS::Yarc>

=cut

